### ISSUE TITLE
Video for lesson with no extension

### ISSUE THREAD

**Issue by mnabialek** [nothingworksinc/ticketbeast#11]
Hi Adam

For lesson Refactoring "Long Parameter List" Using "Preserve Whole Object" the video doesn't have extension, so you need to manually add it after downloading. Probably it should be added because someone might not guess you need to add it manually ;)

**Comment by adamwathan** [comment]
Seems like it's good now, there was a minute there where I replaced the video with another version so maybe something was weird on Vimeo's end. Thanks for the heads up regardless!
