### ISSUE TITLE
Persist video volume between page reloads

### ISSUE THREAD

**Issue by markgp** [nothingworksinc/ticketbeast#12]
In a similar vein to #4, it would be nice if the video player also remembered the volume setting if possible.

**Comment by adamwathan** [comment]
Done!

**Comment by svenluijten** [comment]
🙌

On Dec 22, 2016 16:12, "Adam Wathan" <notifications@github.com> wrote:

Done!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nothingworksinc/ticketbeast/issues/12#issuecomment-268819355>,
or mute the thread

**Comment by markgp** [comment]
Brilliant, thank you!
