### ISSUE TITLE
TDD - backwards

### ISSUE THREAD

**Issue by neilakapete** [nothingworksinc/ticketbeast#13]
It's there any scope for an example of trying to engineer TDD for existing code? I know that doesn't make sense but with so much code out there that is untested it is inevitable that at some point we will come across code that needs tests and it would be interesting to see your approach.

**Comment by apbassi89** [comment]
This is my exact situation. I'm looking over a rather large Laravel project which happens to have no tests. The project well built, aside from the lack of testing, but knowing where to start/some solid strategies would go a long way.

**Comment by mabadir** [comment]
Yes, I'd like to learn how to build tests for existing code and engineer our way through that.
Great course by far.


On December 20, 2016 at 6:19:44 AM, Alessandro Bassi (notifications@github.com<mailto:notifications@github.com>) wrote:

This is my exact situation. I'm looking over a rather large Laravel project which happens to have no tests. The project well built, aside from the lack of testing, but knowing where to start/some solid strategies would go a long way.

**Comment by alexzabolotny** [comment]
You might want to look at "Working Effectively with Legacy Code" a book by Michael C. Feathers. He also was a guest on Full stack radio IIRC.

**Comment by rodericktech** [comment]
This is the book I was going to recommend as well.  Adam mentioned it to 
me several months ago and I picked it up, and it's quite good.

**Comment by adamwathan** [comment]
"Working Effectively with Legacy Code" is definitely the ultimate resource for this kind of info; the whole book is dedicated to strategies you can use to add tests to existing code so you can refactor with confidence, can't recommend that book enough 👍 

The goal of Test-Driven Laravel is to be an awesome resource on building an app from start to finish using TDD which already makes it a massive course, so unfortunately I won't be covering testing legacy code, but the principles and strategies should still give you a lot of tools that you can use to get existing code under test.

Again, definitely pick up Michael Feathers' book, it's fantastic!

https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052
