### ISSUE TITLE
Part 1.6: A request to [http://localhost/concerts/1] failed. Received status code [404].

### ISSUE THREAD

**Issue by Mrkisha** [nothingworksinc/ticketbeast#15]
Even though I've followed video and checked the files with the code in video 4 times, I still get the error `A request to [http://localhost/concerts/1] failed. Received status code [404].`.

`No query results for model [App\Concert] 1`

Test:
```php
    /** @test */
    function user_cannot_see_unpublished_concerts()
    {
        $concert = factory(Concert::class)->create([
            'published_at' => null,
        ]);

        $this->get('/concerts/' . $concert->id);

        $this->assertResponseStatus(404);
    }
```

Controller:

```php
    public function show($id)
    {
        $concert = Concert::whereNotNull('published_at')->findOrFail($id);

        return view('concerts.show', ['concert' => $concert]);
    }
```

**Update**

After very close inspection on @adamwathan cli, I've noticed the command `./vendor/bin/phpunit ./tests/features/ViewConcertListingTest.php --filter user_cannot_see_unpublished_concerts`, which gives me green.

The command that gave me error was `./vendor/bin/phpunit ./tests/features/ViewConcertListingTest.php`

**Comment by adamwathan** [comment]
Hey @Mrkisha, yeah there are a few steps in the lessons where the whole suite isn't passing yet and we're only working on individual test functions rather than whole files. Sounds like you're not missing anything and have all the code correct 👍

**Comment by Mrkisha** [comment]
@adamwathan by finishing next video, all tests went green. Thanks you answering anyway.
