### ISSUE TITLE
factory states

### ISSUE THREAD

**Issue by prolonginc** [nothingworksinc/ticketbeast#16]
so this might be a silly one, am i missing something  in the video you received a faker instance in the call back for the factory states 

 ```
   $factory->state(\App\Concert::class,'published',function($faker){

        return [
            'published_at' => Carbon::parse('-1 week')
        ];

    });

```
but faker was never used unless i am missing something i believe the following passes just fine 
```

   $factory->state(\App\Concert::class,'published',function(){

        return [
            'published_at' => Carbon::parse('-1 week')
        ];

    });

```
Please Clarify thank you.

**Comment by simondotwhite** [comment]
Please correct me if I'm wrong, but I think it's just so that the factory has access to the faker instance. Since the factory doesn't use it it's fine.

**Comment by martonbaranyai** [comment]
Yeah I think so. You can leave the parameters out if you don't use them in your function.

The other side of the coin, you can call a php function with more parameters than it expects, that's just fine

**Comment by svenluijten** [comment]
It's functionally the same as what @martonbaranyai describes above. Internally, Laravel attempts to call the closure you give it as a third parameter (the `function () {}`) and gives it an instance of Faker. It would look something like this internally: 

```php
function state($concrete, $state, $closure)
{
    // do whatever with the concrete class name and state

    $closure(new Faker);
}
```

In short, you're right, the Faker instance is optional. 😄

**Comment by adamwathan** [comment]
Yep everyone here is right, Laravel will pass that Faker instance for you to use, but you aren't required to actually accept the parameter if you don't want to.

I left it there for consistency, even though that particular factory doesn't make use of it.

Any other questions about it happy to help!
