### ISSUE TITLE
Stripe API key or secret?

### ISSUE THREAD

**Issue by sneako** [nothingworksinc/ticketbeast#17]
In 9.1 and 9.2 you are passing `config('services.stripe.secret')` as the 'api_key' to Stripe. Shouldn't it be `config('services.stripe.key')`?

**Comment by morloderex** [comment]
@sneako No the `services.stripe.key` is the `publishable key` which is used only on the frontend to make api calls for retrieving one time used token. When we create a charge we need to use the secret key.

**Comment by sneako** [comment]
Ah ok, so they are both keys, but one is secret.
