### ISSUE TITLE
How do I show the names of passing tests and assertions?

### ISSUE THREAD

**Issue by amite** [nothingworksinc/ticketbeast#2]
I was thinking, it would be nice to show the names of the tests and the assertions that were passing to a stakeholder rather than just 'OK (1 test, 2 assertions)'

How do I enable this with phpunit?

**Comment by ELD** [comment]
Using the `--testdox` flag seems to do the trick.

Example usage:
```
ticketbeast % vendor/bin/phpunit --testdox
PHPUnit 5.6.7 by Sebastian Bergmann and contributors.

ViewConcertListing
 [x] User can view a published concert listing
 [x] User cannot view unpublished concert listings

Concert
 [x] Can get formatted date
 [x] Can get formatted start time
 [x] Can get ticket price in dollars
 [x] Concerts with a published at date are published
```

**Comment by amite** [comment]
Oh nice

**Comment by drbyte** [comment]
I agree: `--testdox` is best

`--debug` gives another output, more for devs than stakeholders though --- while it's probably not what you're after in this situation, it's helpful to know it exists.
