### ISSUE TITLE
Poor editing

### ISSUE THREAD

**Issue by mizansyed** [nothingworksinc/ticketbeast#20]
I find some things are fast paced too follow and not synced, e.g. https://course.testdrivenlaravel.com/lessons/module-1/refactoring-for-speed. You show how various refactoring reduced the test timings, but show the result screens for 200ms. There are other sections where your voice is de-synced or frames are skipped or too pacey for someone to follow. Frustrating and poor editing. I am reviewing the video for my team and learning new things at the same time - so far this editing makes it not recommendable, although the content is good so far.

**Comment by adamwathan** [comment]
Hey @mizansyed sorry about that, but for issues like this please email directly at adam@testdrivenlaravel.com

I just watched that lesson myself and didn't see any issues with out of sync audio, and when I was showing the increase in speed, every time that I said out loud matched what was in the video.

At about 5:50 I run the tests while using `create` and get the following results:

384ms
331ms
313ms

After switching to `make` and disabling the database migrations, the results are:

173ms
140ms
122ms

Can you try downloading the videos and watching them locally in case something weird is happening for you when streaming them? I actually put a lot of time and effort into editing the screencasts to be as polished as possible, so I'm very surprised to hear you're having issues.

**Comment by bmadigan** [comment]
@mizansyed I found that a previous version of Chrome was causing some video delays for me. I upgraded and all my video problems went away.

I have been watching Adam's tutorials on 1.5 speed and I've been able to keep up (with the odd 'pause') of course.

Maybe try a different browser to double check.

**Comment by drbyte** [comment]
I've had no issues at all with the videos or the sync with the audio. 
I'm honestly very pleased with the high quality of the editing, and of course the lessons/content.

**Comment by bmadigan** [comment]
I should probably state, that the video problems for me wasn't actually TicketBeast, but Youtube, Netflix, basically all videos. I'm find the editing very, very good. Especially with the new iMac 👍

**Comment by ndeet** [comment]
Can also confirm that there have been no glitches in audio quality for me at all. More likely to be a browser or connection problem.

**Comment by martonbaranyai** [comment]
Yep, same on me, no problems and very pleased with the quality. I’ve downloaded and watched all videos locally, since I have poor internet connection usually
