### ISSUE TITLE
phpunit not running all tests

### ISSUE THREAD

**Issue by fimfarum** [nothingworksinc/ticketbeast#23]
Hi,

I have an issue running phpunit on the whole suite.
The behaviour is like this:
- when I run just phpunit I have no output
- when I run phpunit tests/units all tests are run from tests/units
- when I run phpunit tests/features no output
- when I run phpunit tests/features/fileTest.php that test is run

I use the same phpunit.xml as the current one from github. I tried to fiddle with it thou but I couldn't make it run more tests.

Did anyone else run into this?

**Comment by svenluijten** [comment]
Try running `./vendor/bin/phpunit`.

**Comment by fimfarum** [comment]
That's exactly the command I run.

The problem is that it only works on the units subfolder and when calling individual files from features subfolder.

**Comment by slashequip** [comment]
Are you running on a clean Laravel install or an existing project?

**Comment by slashequip** [comment]
Oh and might be helpful to share your phpunit.xml file?

**Comment by fimfarum** [comment]
It's a clean install. The .xml file below, but it's exactly the one from this repo.

`<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
    </php>
</phpunit>`

**Comment by slashequip** [comment]
Ok odd that you would be having issues on a clean install.

What is your global version of PHPUnit vs the repo's version? I know I had some odd behaviour when they were different, not showing colours and something else.

**Comment by fimfarum** [comment]
I'm working on C9. I used the default php setup for the VM and a clean laravel install. 
So phpunit was only installed by composer locally in the project.

**Comment by martonbaranyai** [comment]
I think I had this error before, it was due to my local php config

Add this to the <php> part of the xml:
<ini name="display_errors" value="On" />
<ini name="display_startup_errors" value="On" />

Then you should at least see the fatal error msg causing the no output, at least that was the situation with me..

Az iPhone-omról küldve

2017. jan. 19. dátummal, 10:23 időpontban fimfarum <notifications@github.com> írta:

**Comment by fimfarum** [comment]
That was it... I had a compile error inside one of the tests (silly one at best) and I was able to identify and fix it. It now works properly.

Thanks a lot @martonbaranyai.
