### ISSUE TITLE
Call to undefined method Tests\Feature\ViewConcertListingTest::visit()

### ISSUE THREAD

**Issue by joshuabromero** [nothingworksinc/ticketbeast#24]
Hey Adam,

I spun up a new instance of Laravel 5.4 and started the course but hit a wall with the following error:

`Error: Call to undefined method Tests\Feature\ViewConcertListingTest::visit()`

I dug into the code and found that they have removed the InteractsWithPage class in favor of Laravel Dusk. Should I just roll back to Laravel 5.3?

**Comment by adamwathan** [comment]
I'd recommend just pulling in this package which brings that stuff back for
5.4:

https://github.com/laravel/browser-kit-testing

**Comment by joshuabromero** [comment]
That did it. Thanks, Adam.
