### ISSUE TITLE
ViewConcertListingTest

### ISSUE THREAD

**Issue by petericebear** [nothingworksinc/ticketbeast#29]
Hi Adam,

Havent touched the files lately and started again after the video: https://course.testdrivenlaravel.com/lessons/module-2/faking-the-payment-gateway. But now I am getting the following error.

There was 1 error:

1) ViewConcertListingTest::user_cannot_view_unpublished_concert_listings
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Concert] 1

The full code is from the Part 1.6. Any thoughts?

```
        $concert = factory(Concert::class)->states('unpublished')->create();

        $this->get('/concerts/'.$concert->id);

        $this->assertStatus(404);
```

Greetings Peter

**Comment by petericebear** [comment]
Nevermind it should have been: $this->assertResponseStatus(404);

**Comment by christophrumpel** [comment]
I'm having the same error @petericebear , changing the assertion name did not help. Did you change anything else ?

```php
public function user_cannot_view_unpublished_concert_listing()
    {
        $concert = factory(Concert::class)->states('unpublished')->create();
        $this->get('/concerts/'.$concert->id);

        $this->assertResponseStatus(404);

    }
```

Error: `No query results for model [App\Concert] 1`

**Comment by adamwathan** [comment]
Hey @christophrumpel, can you check your `app/Exceptions/Handler.php` file and take a look at the `render` method in case you are re-throwing the exception? That's something I recommended in the course when trying to get better errors when something goes wrong at the HTTP level, but it works against you when you actually *need* the exception to be caught properly and turned into a response, like we want with `ModelNotFoundExceptions`.

**Comment by christophrumpel** [comment]
Hey @adamwathan , yep that was it! I forgot about that exception 😬 Thanks for the hint! 👍

**Comment by mattkoch614** [comment]
Apologies if this is obvious, but I'm missing what I need to change here. I'm just starting to go through the course and I'm stuck on this same error.  It seems to stem from the ``findOrFail`` method in the controller, because it does in fact fail - there is no published concert for the given ``id``.

**Comment by adamwathan** [comment]
Hey @mattkoch614, double check that you aren't disabling exception handling, either via the `disableExceptionHandling` method or by editing the `render` method in `app/Exceptions/Handler.php` to rethrow exceptions.

If that's not it, push your code to a repo I can see and I'm happy to pull it down and help you troubleshoot!

**Comment by mattkoch614** [comment]
@adamwathan - Wow - thanks, what a fast response! I was just typing a reply - this was my fault :( - I had been disabling exception handing in ``TestCase`` ``setup()`` method without noticing...I'm all good.

**Comment by FatBoyXPC** [comment]
@mattkoch614 if you have upgraded to 5.5, and want to continue to use `withoutExceptionHandling()` in your `setUp()`, I believe you can `$this->withExceptionHandling()` in your test methods to re-enable it. Don't quote me on that, but it's worth a shot!
