### ISSUE TITLE
Mark lessons on the website as 'watched'

### ISSUE THREAD

**Issue by negoziator** [nothingworksinc/ticketbeast#3]
I hope it's okay it put this here :) @adamwathan  ?

I would (and i hope others will too) - really appreciate if there was an opportunity, to see which of the lessons, is seen and which is not.

**Comment by Morpheus-ro** [comment]
You have the blue link color to see where are you left or better said what is selected. If you watch it all one after another that you can use that like "watched". Just an opinion ..

![test driven laravel](https://cloud.githubusercontent.com/assets/10401797/20877998/81dac3ac-bacc-11e6-8619-eb951b8b1750.png)

**Comment by nikush** [comment]
Yes

**Comment by vedovelli** [comment]
Also autoplay!

**Comment by alexbowers** [comment]
@Morpheus-ro It is quite useful if you use multiple machines to see where you got up to though

**Comment by negoziator** [comment]
I use multiple machines myself, which was what got me to think on it, the first time.

I often sit after work, and take 1-2 hours of whatever ( in this case, its Laravel TDD )
.. then of course theres all the sundays at home :)

**Comment by adamwathan** [comment]
Yeah totally agree on this, will try to get something implemented soon 👍🏻

This whole course app was built in the 11th hour because the platform I was planning to use was just not going to deliver the experience I wanted, so it's definitely a work in progress!

**Comment by jcorry** [comment]
> This whole course app was built in the 11th hour because the platform I was planning to use was just not going to deliver the experience I wanted, so it's definitely a work in progress!

It's really great. I even appreciate how the content delivery system I watch the lessons through basically follows the same pattern as the app we're building. "Build exactly what you need".

Another feature to consider would be advancing the play head to it's last place on the timeline...so if I leave a page during playback, I resume playback from that spot when I come back to the page.

**Comment by negoziator** [comment]
Should i remain the 'issue' open ?

Well on 11 hours i guess your excused, some features are missing :)

Dont forget to test it when you implement it though ;-)

**Comment by alex-LE** [comment]
@adamwathan maybe you can publish the source code (as a private repo) and the community can send you pull requests with features they want?

**Comment by adamwathan** [comment]
Closing this for now as basic "mark watched when finished" functionality is now in place 👍  Room for future improvements still for sure but can handle those in future discussions 😊
