### ISSUE TITLE
Please add link to the video course page

### ISSUE THREAD

**Issue by ivuorinen** [nothingworksinc/ticketbeast#30]
Thank you Adam for the great video course!

It would be great to have [the link to the course login page](https://course.testdrivenlaravel.com/login) as project homepage, or in the readme.

**Comment by adamwathan** [comment]
Hey @ivuorinen thanks! Good point, I do have a link to login on the early access page, but I should add one to the main testdrivenlaravel.com site as well.

**Comment by svenluijten** [comment]
Related to this, can you add a link to the course at the top of this repository? I find myself going to this repository, hoping to find a link to the course and there is none. ![this is what I mean](http://i.imgur.com/qxUFIn4.png)

**Comment by adamwathan** [comment]
@svenluijten Good idea, done!
