### ISSUE TITLE
Persist video quality between page reloads

### ISSUE THREAD

**Issue by alexzabolotny** [nothingworksinc/ticketbeast#4]
When on traffic limited internet<sup>*</sup> I tend to switch YouTube and other video players to lower quality. This usually does not affect content consumption (especially true for conference talks and well done screencasts).

Would be convenient to have video player remember the last used quality setting (HD or SD) when switching to next lesson or opening the course after some time.

<sup>*We do have this thing in Europe that first N Gb are at full speed and after that you get crappy 3Mbps for the rest of the month.</sup>

**Comment by vmitchell85** [comment]
Can we also retain speed settings?

**Comment by adamwathan** [comment]
Both now done! Let me know how it's working for you.

**Comment by vmitchell85** [comment]
BOOM! - Works Great! Thanks!
