### ISSUE TITLE
72. Asserting Against View Data

### ISSUE THREAD

**Issue by spyric** [nothingworksinc/ticketbeast#40]
Hello, Adam! Thanks for new course update

I have a question about verification on order in  (https://github.com/nothingworksinc/ticketbeast/commit/8ac3ab3441cbaac95cf39eacf26b74cb0e39bd9d#diff-49cec98f74afc24d68b53d00c100cdfdR34)

Will be best approach to use  `is` method on the model? 
(https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php#L965)

Because now If we pass another object to order variable in view, with the same id this test will pass but in fact it's wrong situation.

**Comment by adamwathan** [comment]
@spyric Nice I didn't know about that method! Definitely nicer to use that. I'm not too worried about the "pass the wrong model with the same ID" bug potential but it's still nice that this covers that regardless 👍

**Comment by petericebear** [comment]
So then it would be?
```php
$response->assertViewHas('order', function ($viewOrder) use ($order) {
            return $order->is($viewOrder);
        });
```

Am I correct?

**Comment by adamwathan** [comment]
Yup!

**Comment by markinigor** [comment]
Be careful,  this method sometimes works not how you expected.
```
$modelJustCreated = Model::create(['title'=>'blaBla']);
$modelFromDB = Model::where('title', 'blaBla')->first();
$modelFromDB->is($modelJustCreated) === false;
```
When Eloquent model use some create methods it sets property 'connection',  but when you retrieve from database, property 'connection' will be Null

**Comment by morloderex** [comment]
This is to be expected because the where method doesn't return an instance of Eluquent Builder but the underlying Query builder instance.. And therefore the instance will be null because of some missing eluquent events. As far as i know..

**Comment by juukie** [comment]
It is good to know though. Thanks folks!

**Comment by adamwathan** [comment]
> Be careful, this method sometimes works not how you expected.
>
> When Eloquent model use some create methods it sets property 'connection', but when you retrieve from database, property 'connection' will be Null

Just a note, I ran into this myself and talked to Taylor about it and confirmed it was a bug; we got a fix in for it a few patch releases ago 👍 So it's safe to use `is` for these sorts of things now for sure!
