### ISSUE TITLE
(Somewhat OT) Testing file downloads

### ISSUE THREAD

**Issue by ohnotnow** [nothingworksinc/ticketbeast#42]
'Allo,

I'm in the process of migrating an app to 5.4 and as part of that I need to test file downloads (it's one of the main user-facing features of this particular app).  In the olden days I could do things like :

```
$response = $this->get(route('user.whatever', $user->id));
$this->assertEquals(true, $response->getFile()->whatever());
```

But in 5.4 that seems to be gone - trying to get the response from a download() or file() response just throws an exception :

```
$response = $this->get(route('user.whatever', $user->id));
...
UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given
```

I'm stuck for ideas!  There's a [GitHub issue](https://github.com/laravel/framework/issues/18049) open on this - but if there's a better work-around I'll be delighted - I'm beginning to eye up file_get_contents() in desperation ;-)

**Comment by martonbaranyai** [comment]
I think I got it working with a fake :)

https://gist.github.com/martonbaranyai/74210e8377f5f13e475d2649d099061a

Maybe not the nicest ever, but could be a starting point

(“File” is a model, we store files in the db not on disk)

**Comment by ohnotnow** [comment]
@martonbaranyai thanks for that :-) I was hoping to avoid having to fake things too much - possibly just laziness ;-)  It seems a bit of a useful feature to remove without an obvious replacement though given all the shiny new stuff - I can test drag'n'dropping javascript elements and websockets with ease, but not downloading a file ;-)

**Comment by adamwathan** [comment]
Ah man that sucks. The root problem really is that TestResponse is implemented via inheritance, it makes everything so unbelievably messy in this regard. 

I'm working on a small PR to reimplement the whole thing with composition and delegation, I think it will simplify everything a lot.

Wish me luck! 👀

**Comment by adamwathan** [comment]
Here she is: https://github.com/laravel/framework/pull/18089

**Comment by ohnotnow** [comment]
@adamwathan wow! if you ever end up in 'sunny' Scotland - I owe you a whisky or three!  Thank you so much! :-D
