### ISSUE TITLE
Package testing?

### ISSUE THREAD

**Issue by kilrizzy** [nothingworksinc/ticketbeast#45]
Would we expect to see any sort of info on extracting some of our logic into a package and writing tests for that in this course?  If not any resources for doing this as the workflow is something I've struggled with for some time

Thanks!

**Comment by ivanvermeyen** [comment]
I would be very interested in this aswel... 👍 
Especially in how to write feature / integration tests when you just have a package and not the entire Laravel app...

**Comment by joselfonseca** [comment]
For this you can use https://github.com/orchestral/testbench which creates a Laravel app for the package testing. I've been using it for years and works like a charm. In fact i think Taylor is also using it. Saw a tweet about it the other day.

**Comment by kilrizzy** [comment]
Very cool I'll give testbench a shot!

**Comment by adamwathan** [comment]
I don't think I'll be able to fit it in to this course because it's already going to be pretty massive, but I'll keep it in mind for the future, maybe can at least do something for the blog 👍🏻

**Comment by kilrizzy** [comment]
Awesome

**Comment by martinolson** [comment]
Hi Adam, 
This course is excellent and has been very helpful. I'd be happy to pay for a Test Driven Package Development (TDPD) course if this is something you decide to do in the future.
