### ISSUE TITLE
TokenMismatchException since upgrade

### ISSUE THREAD

**Issue by GaryClarke** [nothingworksinc/ticketbeast#46]
Wonder if anyone can make a suggestion.

Since upgrading to L5.4 a TokenMismatchException is thrown every time I call $this->json(). It's a total mystery...I've followed the course exactly as Adam has done it.

This is also happening in another project which I upgraded and only happens when extending TestCase and not when extending BrowserKitTestCase.

Any help appreciated, Gary

**Comment by pdbreen** [comment]
Check your middleware groupings in Http\Kernel.php.  Sounds like you may have the VerifyCsrfToken middleware applied to API routes.

**Comment by zoransa** [comment]
artisan key:generate

**Comment by GaryClarke** [comment]
The middleware is just on web and key generate doesn't fix it. Looks like
I'll have to try a fresh install :(

**Comment by martonbaranyai** [comment]
I did have a similar problem just yesterday. What fixed for me was correcting a misconfig in my config/sessions.php. Namely I set the domain name to the production domain name. And then it was not working on my local, since the domain name was different, and the “session” just did not stick, resulting in the csrf token not sticking in the session, causing the csrf to no match against “nothing”

**Comment by GaryClarke** [comment]
Hi Marton, I'm not sure what you mean. Did you fix it? What did you set the
session domain to exactly?

**Comment by martonbaranyai** [comment]
Yeah it fixed it.

It had “eastsong.it” as the value, and I set it back just null (what was there before I changed it)

**Comment by GaryClarke** [comment]
Ok cheers. Mine was set to null anyway so I've still got the problem. This
is a total mystery!

**Comment by GaryClarke** [comment]
I've done a fresh install and I've still got the problem. The strangest
thing is that the ViewConcertListingTest works, it's just the
PurchaseTicketTicketsTest that throws

1)
Tests\Feature\PurchaseTicketsTest::customer_can_purchase_tickets_to_a_published_concert

Illuminate\Session\TokenMismatchException:


as soon as $this->json() is called.

**Comment by GaryClarke** [comment]
I can get rid of it by flushing the session in the test set up. Just not
sure why I'm getting this and no one else.

**Comment by adamwathan** [comment]
Hey @GaryClarke can you upload a small example repo that demonstrates the issue? Will gladly pull it down and see if I can figure it out!

I just ran a `composer update` on the TicketBeast repo myself to make sure I'm on the latest of everything and not having that issue here 🤔

**Comment by GaryClarke** [comment]
Sure Adam, cheers for your help. Shall I just upload my tests dir?

**Comment by adamwathan** [comment]
So it looks like you should hit this line in the middleware:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L87-L90

I would start there to debug.

Find that file in the vendor directory and temporarily change it to:

```
protected function runningUnitTests()
{
    dd($this->app->runningInConsole(), $this->app->runningUnitTests());
    return $this->app->runningInConsole() && $this->app->runningUnitTests();
}
```

...to find out which of those checks is returning false.

If I had to guess, I bet something is configured oddly that is causing `runningUnitTests` to come back false. It checks to see if the environment is set to `testing`, so there might be something going on that has your tests running as a different environment.

**Comment by GaryClarke** [comment]
Yeah, you're right...it came back as true / false. For some reason it's not
running in the testing environment. My phpunit.xml is correct and this has
just started since the upgrade. Strange...any ideas?

**Comment by adamwathan** [comment]
What environment is it running as? `dd(app()->environment())` I believe will tell you.

What's your dev environment look like? I saw someone had a similar issue the other day using Homestead.

**Comment by GaryClarke** [comment]
It's running as local and I'm using Homestead also. It's the same install
I've been using for about 18+ months and it's never caused me any problems
before. You think a complete Homestead re-install?

**Comment by adamwathan** [comment]
This was the problem for the other person I talked to:

https://github.com/laravel/homestead/issues/411

Check your Homestead.yaml to see if there is an environment variable set, if so remove that entire `variables` section and try re-provisioning the virtual machine (or whatever it is you're supposed to do with Homestead when you make changes 🤷‍♂️ )

**Comment by svenluijten** [comment]
Try running the test suite from your local machine instead of from within the Homestead box. Alternatively, check `phpunit.xml` and see if you can spot any odd environment variables.

> (or whatever it is you're supposed to do with Homestead when you make changes 🤷‍♂️ )

`vagrant reload --provision` should do the trick there 😉

**Comment by thecrypticace** [comment]
Have you tried running php artisan config:clear (not config:cache)?

**Comment by GaryClarke** [comment]
Yeah, tried config:clear etc. but with no joy.

Good news though, removing the vars from my 150 year old yaml file, as Adam
suggested, did the trick.

Thanks to everyone that tried to help out. Great little forum this...love
it.

**Comment by adamwathan** [comment]
Awesome! Glad that got it sorted.

**Comment by thecrypticace** [comment]
That is so strange. I thought the env vars only affected php-fpm not the cli, weird. I run tests inside my vm all the time.

Glad you got it all worked out!

**Comment by GaryClarke** [comment]
Yeah...this one really threw me. Upgrades usually go pretty smoothly. Cheers for getting involved.
