### ISSUE TITLE
Composer Package "stripe/stripe-php": "^4.3", vs "laravel/cashier": "~7.0"

### ISSUE THREAD

**Issue by smeikle82** [nothingworksinc/ticketbeast#48]
Hello, 

I was wondering why stripe/stripe was being used vs the laravel/cashier. Is one recommended over the other, or was it meant for simplicity?

**Comment by adamwathan** [comment]
Hey @smeikle82! Cashier is meant for recurring subscription billing in SaaS apps; since we just need to do individual charges for people purchasing tickets, it makes more sense to just use Stripe's library directly 👍🏻

**Comment by smeikle82** [comment]
Thank you for that quick reply. Really enjoying the course so far!
