### ISSUE TITLE
Improvement: ticket reservation

### ISSUE THREAD

**Issue by renedekat** [nothingworksinc/ticketbeast#51]
First of all: Great work.

Secondly, as an improvement I think it would be nice if the front-end made a call to reserve tickets, the moment you select a quantity. Before providing any payment details. Once reserved, it should inform the user that the tickets are reserved for the next X minutes.  

Currently the user is only informed of insufficient availability after payment details are provided.

This will require a CRON job that cleans up reservations constantly as well.

**Comment by adamwathan** [comment]
Thanks! I think your idea is a good one but I left that out intentionally, just because we'd never finish this course if we tried to take things to Ticketmaster-level sophistication.
