### ISSUE TITLE
How to test this?

### ISSUE THREAD

**Issue by ebisbe** [nothingworksinc/ticketbeast#54]
Hello Adam,

I've made this littlep pice of code that I'm not sure how tot test it. Can you guide me?

```
 /**
     * @param Request $request
     */
    public function byRequest(Request $request)
    {
        if ($request->getQueryString()) {
            $this->byLink($request->url());
        }
    }
```
The byLink() method is test it. And the byRequest method is test it with an acceptance test. But I wonder if this function should be test it as a unit test.

thanks

**Comment by svenluijten** [comment]
Hey @ebisbe, I'll repost what Adam posted in another issue (#53):

> Please be conscious that when you open an issue on this repo, 2000+ people get an email about it 😬

> Happy to try and help but I think somewhere like the Laracasts forum is a better place for general testing questions like this, vs. specific questions about something in the course.

This just seems like way too general a question that falls out of the scope of this course. 🙂
