### ISSUE TITLE
How about file uploads

### ISSUE THREAD

**Issue by axyr** [nothingworksinc/ticketbeast#6]
Is there any info about testing file uploads in this course?
I can't find it?

**Comment by zaknesler** [comment]
I would love that, too. (:

Not sure how it would be implemented in a course like this. Maybe concert images?

Edit:

Possibly with verification that it is uploaded to S3?

**Comment by bmartus** [comment]
*Uploading and Processing Poster Images* is listed in the future course content.

https://course.testdrivenlaravel.com/early-access

**Comment by adamwathan** [comment]
Hey @axyr yeah that is coming in a future module!

**Comment by zaknesler** [comment]
Awesome!

@adamwathan How many modules do you predict the course will have?

**Comment by axyr** [comment]
I want it now ;)

Thanks though for the quick responses.

**Comment by adamwathan** [comment]
Here's the general outline of where things are going next:

https://gist.github.com/adamwathan/dabbac0bbb7829fd3dd2d6e130bed77b

Based on how things have gone so far, I expect some of these module will end up getting split into multiple modules when I notice things I need to cover in more detail that were hard to predict up front.

The next batch of lessons will be out on Monday :)

**Comment by afsardo** [comment]
@axyr But in general when you need to test a real file upload it's quite simple.

Just pass it as a normal parameter in this form:

```php
$file = new \Illuminate\Http\UploadedFile([path], [originalName], [mimeType], [size], [error], [test]);
```

(real example)
```php
use \Illuminate\Http\UploadedFile;

$filePath = storage_path('app/tests/test-video.mpg');
$file = new UploadedFile($filePath, 'test-video.mpg', 'video/mpeg', filesize($filePath), null, true);
$response = $this->json('POST', '/api/upload', [
    'file' => $file
]);
```

**Comment by axyr** [comment]
Not even on slack or irc I got a response this fast :)

Thanks!!

**Comment by afsardo** [comment]
Power of the Laravel Community and the people around it ^^

**Comment by Hesesses** [comment]
The Course Outline looks amazing!
So far I feel this has been the best way I have ever used my money 🎉 

Do you have any timeframe when those remaining courses will be published?

**Comment by adamwathan** [comment]
Hey @Hesesses thank you! I'm trying my best to put out 8-10 new lessons per week until all of the material is covered. Hoping for end of January, maybe a bit longer if it takes more videos than expected to cover certain topics.

Either way should have plenty of content coming out a steady pace to check out in the mean time! 👍🏻
