### ISSUE TITLE
[REQUEST] Ability to reset all videos to unwatched

### ISSUE THREAD

**Issue by ghost** [nothingworksinc/ticketbeast#64]
Hi Adam, thanks for an absolutely fabulous course, any chance of adding a feature to the tutorial site allowing videos to be set back to unwatched, I'm sure I'm not the only one looking forward to working my way through the course a second time, back to back.

Thanks in advance

Pete

**Comment by adamwathan** [comment]
I'll try get this in there after Laracon next week! In the mean time, if anyone would ever like me to reset that data for them just shoot me an email at adam at testdrivenlaravel dot com, happy to clear it out for you.

**Comment by ghost** [comment]
Thanks Adam, have sent you an email requesting a reset

**Comment by hulkur** [comment]
Idea: let people PR new features
AC: TDD

Like a course test :)

**Comment by martinbean** [comment]
@adamwathan Was this ever implemented? Just came here to propose the same idea, but see this was opened in July.

**Comment by adamwathan** [comment]
Hasn't been implemented but still happy to reset it manually for anyone if asked!

**Comment by martinbean** [comment]
> Hasn't been implemented but still happy to reset it manually for anyone if asked!

@adamwathan Would you be able to run that lovely `DELETE * FROM watches` query for me in that case? 😆

**Comment by jkniest** [comment]
I hope he will run something like:

```sql
DELETE * FROM watches WHERE user LIKE 'martinbean';
```

I don't want to lose my watches :-D

**Comment by martinbean** [comment]
> I hope he will run something like…

I hope he’s using a foreign key 👀

**Comment by svenluijten** [comment]
Sorry to pile on, but about 1,600 people get an email every time a reply is posted here. Keep the chit-chatting to a Slack room or something 🙂

**Comment by danmatthews** [comment]
@svenluijten - if you'd like to not receive the emails you can adjust your github notification preferences for this repo. Thanks.
