### ISSUE TITLE
PHPUnit exhausted memory

### ISSUE THREAD

**Issue by ivanvermeyen** [nothingworksinc/ticketbeast#7]
Hello,

How much memory is PHPUnit supposed to use?
My test suite ran perfectly before, but after updating Homebrew etc., I got this error:

```
...............................................................  63 / 168 ( 37%)
............................................................... 126 / 168 ( 75%)
.................................PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)
```

When I run a part of my tests (most of them):

```
...............................................................  63 / 128 ( 49%)
............................................................... 126 / 128 ( 98%)
..                                                              128 / 128 (100%)

Time: 12.54 seconds, Memory: 124.00MB

OK (128 tests, 459 assertions)
```

Should I increase the memory limit or is there likely something wrong with my tests?
I'm doing quite a lot of tests that create (and get) records in (from) the database.

Thanks @adamwathan for the excellent videos!

**Comment by vernard** [comment]
This is alarming:
```
Time: 12.54 seconds, Memory: 124.00MB
```

As @adamwathan said, we want tests to be extremely fast, or else we will not run them.

Can you find out why it's using taking up huge memory?

**Comment by hulkur** [comment]
It's usually print_r/var_dump/var_export trying to output some large object

**Comment by vernard** [comment]
He said:
> I'm doing quite a lot of tests that create (and get) records in (from) the database.

Do you think that would take up this much memory from queries?

@ivanvermeyen When you run test for one feature, how much memory does it use?

**Comment by ivanvermeyen** [comment]
To be honest, I will probably need to work on organising my tests better in features etc.

I tracked down which tests were taking up most time and memory. There is one folder with a few TestCases that do a lot of calls like `$this->visit()` and `$this->type()` and `$this->see()` and database assertions.

```
.............................................................     61 / 61 (100%)

Time: 8.49 seconds, Memory: 78.00MB

OK (61 tests, 289 assertions)
```

In one of the videos, Adam talked about how he tries to avoid these UI tests, but that they have both pro's and cons. I already refactored these tests a bit in this mindset (I wrote the original tests before watching the videos). So now I test a form once and then tackle the validation testing like Adam showed us with the `$this->json()` calls. But I do kinda like the assurance that the form works. :)

I see that these tests do take a lot more time to run, so maybe I could separate them in a UI test folder or something and run them separately... 

I guess that it is normal then that it also takes that much memory...

When I move the folder out, It went from:
```
Time: 12.54 seconds, Memory: 124.00MB
OK (128 tests, 459 assertions)
``` 
to: 
```
Time: 3.29 seconds, Memory: 66.00MB 
OK (67 tests, 170 assertion)
```

I still have some other tests in there that use `$this->visit()`, to see if database entries are shown on a page etc. Maybe I should do another refactor run on those files and see how I can tackle it differently. And watch the videos again :)

So much to learn... :)

**Comment by vernard** [comment]
That's a good idea to have a separate tests for UI. But that would also incur duplicate tests that basically does the same thing.

In the end, it's up to you. Adam gave us the options, pros and cons of browser vs end to end testing and it's up to us to decide depending on our personality/requirements.

Here's what I think about this: UI bugs are easily detectable and I have a tendency to test them manually anyway. I can't trust phpunit to make sure in the UI looks good plus works right. So in my case, I'd also use end to end testing. Just my 2 cents.

**Comment by ivanvermeyen** [comment]
Thanks for the insights, it's really helpful to talk/write about this stuff with others :)
Sometimes you have this problem you can't solve, until you explain the problem to another person and then everything is clear suddenly... 
I think it forces your mind to take a step back and rethink / analyse the problem :)

**Comment by vernard** [comment]
Yeah. Somehow similar to the technique where you explain your code to a rubber duck.

Also this is why when we talk about our problem over alcohol, you are helping just by listening.

Cheers man, I'm also a beginner in TDD laravel so I'm learning with you. Thanks for sharing your issue
