### ISSUE TITLE
phpunit error while testing query scopes

### ISSUE THREAD

**Issue by dimitriacosta** [nothingworksinc/ticketbeast#79]
I am getting a weird error in here because when I run phpunit globally I got an error but if I run phpunit from the vendor directory it passes even though they are both in the same version

![screen shot 2018-02-10 at 12 44 02 am](https://user-images.githubusercontent.com/5995547/36059942-d8fcfcd0-0dfb-11e8-9de6-104f62c3f20f.png)

**Comment by manshu** [comment]
You have different versions of phpunit. Use the one inside vendor directory.

**Comment by svenluijten** [comment]
@manshu did you see the screenshot? The last 2 commands he ran both returned the same version:

```bash
$ phpunit --version
# 5.7.27
$ ./vendor/bin/phpunit --version
# 5.7.27
```

**Comment by manshu** [comment]
What php version are you running ?

**Comment by dimitriacosta** [comment]
@manshu I am using php 7.1.14
```bash
$ php -v
# PHP 7.1.14 (cli) (built: Feb  2 2018 08:41:46) ( NTS )
# Copyright (c) 1997-2018 The PHP Group
# Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by dimitriacosta** [comment]
I'm losing my mind here, I went all the way to the lesson 3.7 and I'm still unable to run phpunit globally because I got this error.

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

F.......................                                          24 / 24 (100%)

Time: 1.36 seconds, Memory: 20.00MB

There was 1 failure:

1) PurchaseTicketsTest::customer_can_purchase_tickets_to_a_published_concert
Expected status code 201, got 500.
Failed asserting that 500 matches expected 201.

/Users/dimitriacosta/code/concerts/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:744
/Users/dimitriacosta/code/concerts/tests/features/PurchaseTicketsTest.php:45
/Users/dimitriacosta/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
/Users/dimitriacosta/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:116

FAILURES!
Tests: 24, Assertions: 51, Failures: 1.
```

But if I run the tests from the `vendor/bin/phpunit` file the all pass, even though the phpunit is exactly the same

Can anybody help me with this?

**Comment by kskrlin** [comment]
Which os are you using?
Can you provide a github repo so I can test it locally?

**Comment by dimitriacosta** [comment]
Hi @kikky7 I'm using OS X right now and my repo is in gitlab, however you could clone this repo and reset everything to the commit of this lesson and it will be the same result as you can see below.

![screen shot 2018-02-23 at 8 46 13 am](https://user-images.githubusercontent.com/5995547/36602796-25fa9d56-1876-11e8-9429-523752b04214.png)

By the way, `t` is an alias for global `phpunit`

**Comment by jkniest** [comment]
It would be interessting what this 500 error is. Could you disable exception handling there? And show us the error message you get? 

Edit: Nevermind I have oversaw the first screenshot ^.^ Sorry

**Comment by dimitriacosta** [comment]
It returns this
```
1) PurchaseTicketsTest::customer_can_purchase_tickets_to_a_published_concert
ErrorException: Declaration of Illuminate\Database\Eloquent\Collection::contains($key, $value = NULL) should be compatible with Tightenco\Collect\Support\Collection::contains($key, $operator = NULL, $value = NULL)
```
