### ISSUE TITLE
Playing some videos fails

### ISSUE THREAD

**Issue by mnabialek** [nothingworksinc/ticketbeast#8]
For some videos I'm getting **A network error caused the media download to fail part-way.** A the moment I'm getting it for example https://course.testdrivenlaravel.com/lessons/module-3/outlining-the-first-test-case

It's not a big deal because downloading videos works without a problem, but when I look into Network tab in browser I'm getting:

https://course.testdrivenlaravel.com/lessons/node_modules/videojs-vtt.js/dist/vtt.js - 404 (this is for all videos, also those that work without a problem)

But for this not working video I'm also getting no response from url:

https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/3277/7/191389444/636838905.mp4?token=... (don't including token here).

Refreshing page doesn't help, also this is for sure no problem with my network as other videos are working without a problem (and other sites too).

**Comment by adamwathan** [comment]
Hey @mnabialek sorry about that, the first error sounds like an issue with Vimeo that was hopefully just a temporary thing and sorted out by now.

The issue with the 404 is very bizarre though, what browser are you using?

I found an issue about it here but haven't experienced it myself:

https://github.com/videojs/video.js/issues/2135

**Comment by mnabialek** [comment]
About vimeo, I'm still getting 410 gone with no response. 

About 404 - I'm using Firefox but are you sure valid url is used? When I visit https://course.testdrivenlaravel.com/lessons/node_modules/videojs-vtt.js/dist/vtt.js in Chrome I'm also getting Laravel error **Sorry, the page you are looking for could not be found.**

**Comment by adamwathan** [comment]
Yeah that URL should never actually get loaded, it gets loaded dynamically by video.js when it detects a certain feature is not available, but that feature is definitely bundled in the webpack bundle, so it never requests that URL for me.

Here's a picture of my network tab:

![image](https://cloud.githubusercontent.com/assets/4323180/21080543/a234f6e2-bf7f-11e6-81b6-b9ab86da9716.png)

I just checked in Firefox though and am seeing the same issue, so I should be able to diagnose it now at least.

Can you share the full URL to the Vimeo file that isn't working for you (including the token)? It's embedded in the HTML anyways, anyone who has access to this GitHub repo also has access to those URLs so not worried about keeping it secret.

**Comment by adamwathan** [comment]
I just deployed a fix for the 404 on that weird node_modules thing, but I don't think it's going to change the other issue.

Are you able to test in a different browser to see if that makes any difference? I'll also try and find a VPN through Poland to see if it's a regional issue.

**Comment by mnabialek** [comment]
I cannot repeat it and give you full url with token because it's working now. I also don't know how it works, but now for some urls I don't see vimeo requests at all though video is played without any problems.

I remember I had the same issue with some lesson in Part 1 or 2 about a week ago and after some time it started to working same as it's working now for Part 3.1

**Comment by adamwathan** [comment]
Ok great, glad it's working now. I have to think it's a Vimeo thing but I'll definitely keep my eyes open for it and research if others have run into it and if there's a solution.

Sorry again!

**Comment by mnabialek** [comment]
No problem for me :) I've just created issue just in case more people have this problem

**Comment by adamwathan** [comment]
Cleaning up some issues so going to close this one, let me know if there's any new problems though!
