### ISSUE TITLE
Logged in for Stripe Connect testing?

### ISSUE THREAD

**Issue by bmartus** [nothingworksinc/ticketbeast#88]
For the Stripe Connect tests, am I missing something or do you need to already be logged into a Stripe account before you run the tests for this to work properly?

Would it be better to have Dusk log into the Stripe account?  Or are these slower Dusk tests run so infrequent to really matter?

**Comment by adamwathan** [comment]
Stripe lets you create an anonymous account in test mode during the OAuth flow without being logged in so it should all just work as long as you are using test credentials and not production credentials.
