### ISSUE TITLE
What's the sublime text theme you're using?

### ISSUE THREAD

**Issue by PauloPhagula** [nothingworksinc/ticketbeast#89]

**Comment by EmilMoe** [comment]
I don't know which one he uses, but I can recommend space grey themes

**Comment by adamwathan** [comment]
Throughout the course I use two different ones:

- This light one: https://github.com/sethlopezme/InspiredGitHub.tmtheme
- This dark one: https://github.com/adamwathan/sublime-themes/blob/master/Atom-Dark-lowcontrast.tmtheme

**Comment by PauloPhagula** [comment]
Thanks
