### ISSUE TITLE
Using mocks instead of spies

### ISSUE THREAD

**Issue by mnabialek** [nothingworksinc/ticketbeast#9]
Hi Adam

One question spies instead of mocks (mentioned in lesson  - https://course.testdrivenlaravel.com/lessons/module-7/refactoring-mocks-to-spies ). Question is - do you think it's safe to use spies instead of mocks? I'll show you what you mean.

Our first version of test (with spies):

```php
        $tickets = collect([
            Mockery::spy(Ticket::class),
            Mockery::spy(Ticket::class),
            Mockery::spy(Ticket::class),
        ]);
        $reservation = new Reservation($tickets);
        $reservation->cancel();
        foreach ($tickets as $ticket) {
            $ticket->shouldHaveReceived('release');
        }
```

and our second version of test (with mocks):

```
       $ticket1 = Mockery::mock(Ticket::class);
        $ticket1->shouldReceive('release')->once();
        $ticket2 = Mockery::mock(Ticket::class);
        $ticket2->shouldReceive('release')->once();
        $ticket3 = Mockery::mock(Ticket::class);
        $ticket3->shouldReceive('release')->once();
        $tickets = collect([$ticket1, $ticket2, $ticket3]);
        $reservation = new Reservation($tickets);
        $reservation->cancel(); 
```

When `cancel` method for`Reservation` is implemented like this:

```
        $this->tickets->each(function($ticket) {
           $ticket->release(); 
        });
```

there is no problem - both tests are passing. But what if other developer would like to add something to `cancel` method without changing tests?

Let's assume someone implement something implemented this method now like this:

```
        $this->tickets->each(function($ticket) {
           $ticket->release(); 
           $ticket->reserve();
        });
```

When using tests "with spies" the test will pass although the `cancel` method might don't do what is expected (extra `reserve` call on each ticket. But when using tests "with mocks" it will fail, because we will get error now for this test:

> Method Mockery_0_App_Ticket::reserve() does not exist on this mock object

so if we run tests we will know that something was added that maybe shouldn't be added or maybe we just need to update tests to verify this.

For me although version with mocks it's not as clear as this with spies it's safer to use because tests will probably fail if we run some method that we didn't expected to run when writing test. What do you think about it?

**Comment by adamwathan** [comment]
Hey @mnabialek, this is a really good question!

What you've identified here is basically the only significant downside to using a spy vs. a mock, as you said:

*A spy will blindly accept and record any method thrown at it, a mock will throw an error if it receives any method it wasn't told about in advance.*

Here's my opinion on why I don't worry about this trade off in 99% of cases:

1. **Using a test-driven approach, there's no reason why any code should exist that isn't the result of trying to make a test pass.**


    In your example, you call `$ticket->reserve()` directly after calling `$ticket->release()`, which obviously is not how we actually want the code to end up! 

    But when writing tests first, there's no reason we should be adding that `$ticket->reserve()` call unless a test failure causes us to.

    There's *always* something you could do to the production code that would break it without triggering a test failure.

    Here's an extreme example I use sometimes:

    Imagine we were writing a function that converted `snake_case` strings to `camelCase`.

    We might have a couple of test cases, something like this:

    ```php
    /** @test */
    function snake_case_strings_are_converted_to_camel_case()
    {
        $this->assertEquals('myFancyString', snake_to_camel('my_fancy_string'));
    }

    /** @test */
    function single_words_are_not_changed()
    {
        $this->assertEquals('word', snake_to_camel('word'));
    }
    ```

    Here's what an implementation might look like:

    ```php
    function snake_to_camel($string)
    {
        return lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $string))));
    }
    ```

    But what happens if we decide to do something silly like this in our implementation?


    ```php
    function snake_to_camel($string)
    {
        if ($string == 'banana_sandwich') {
            return $string;
        }

        return lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $string))));
    }
    ```

    Our tests will still pass, even though our code is obviously wrong!

    There's always going to be some sneaky thing you can do to sneak past your test suite, but if you are doing TDD, the odds of doing it by mistake are a lot lower in my experience.

    I'm willing to make that trade-off with spies vs. mocks 99% of the time.

    Sometimes though, you do have a function where based on some logic, you might call method A or method B, and it's important that the right one gets called and the wrong one doesn't.

    In these cases, I would still use a spy, and verify that the wrong method was not called as part of my `assert` phase:

    ```php
    /** test */
    function it_does_something()
    {
        // Some arrange/act code...

        $foo->shouldHaveReceived('methodA');
        $foo->shouldNotHaveReceived('methodB');
    }
    ```

    This doesn't cover the cases where `methodC` gets called by mistake somehow (which a mock would), but again, it's just not a mistake I'm that concerned about catching with my test suite.

2. **Our feature tests work as a safety net against these problems**

    In the example of accidentally calling `$ticket->reserve()` after calling `$ticket->release()`, our higher level feature test would still fail because we would be checking that there were still `x` tickets available but that number would be incorrect.

    You're not guaranteed to always have this sort of thing get caught by your feature tests of course (the "banana_sandwich" example would still be a problem), but it does give you a bit more confidence that things are working correctly at a higher level.

At the end of the day, it really just comes down to the fact that it's impossible to protect against every possible case with your test suite. TDD helps mitigate this by making sure you aren't writing code unless you are doing it to make a test pass, but the responsibility is still ultimately on you to be dilligent and try your best to write error-free code.

The test suite helps *a lot*, but you'll always still have to be on your game, thinking about possible edge cases and error situations to handle.

Hope that helps, and thanks for the thoughtful question!

**Comment by mnabialek** [comment]
Thank you for detailed answer. You are obviously right when talking about TDD and this scenario. The things I'm most afraid of are in using spies vs mocks:

- not each project is using TDD 
- not all people use TDD in valid way
- some programmers don't have enough skills so they can easily bug code and existing tests won't fail which will gave them false feeling everything is fine

Also I wish in my projects tests were so simple as you show here, usually there are much more complex and test lots of things :)

**Comment by adamwathan** [comment]
For sure! There's definitely nothing wrong with using mocks either, in your scenario it sounds like it's better to make the trade-off the other way, have a less consistent test structure in order to be more strict about the mock expectations. It's really just up to you to decide what approach provides more value in your situation 👍🏻 Both have advantages, and both are much better than no tests! 😊
