### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Morpheus-ro** [nothingworksinc/ticketbeast#93]
I think now one did the course until here, hand in hand. In the ViewConcertListTest.php Adam showed the usage on macros but in this test, EditConcertTest.php file there is no macro in the setUp; there is no setUp.

https://github.com/nothingworksinc/ticketbeast/blob/8c6b2cbb248a46db83ebf32de43951acac28ffb7/tests/Feature/Backstage/EditConcertTest.php#L27

**Comment by adamwathan** [comment]
setUp is inherited from the parent TestCase and will run automatically 👍 Are you having an issue getting this test to run properly?

**Comment by Morpheus-ro** [comment]
I probably missed the part in where you say that. Thanks for the fast reply :)
