### ISSUE TITLE
Testing Laravel Scout using a Fake version or mock?

### ISSUE THREAD

**Issue by roarkmccolgan** [nothingworksinc/ticketbeast#95]
I would like to know how to test the functionality of Laravel Scout?
As described in "Faking the payment gateway" lesson I thought I could use the NullEngine of the Laravel Scout Package in my test environment, however for searches it just returns an empty array.

I thought I could resolve my own "fake" implementation of a Scout Engine, much like the nullEngine but actually return something.
Tried of something like this:
```
function can_search_for_a_product()
    {
        $this->app->instance(EngineManager::class, new FakeEngineManager($product));

        $this->withoutExceptionhandling();
        $concert = factory(Concert::class)->create([
            'title' => 'Fake Monkeys'
        ]);

        $searchTerm = "Monkey";
        $response = $this->json('get', "concerts/search/{$searchTerm}");
        $response->assertStatus(201);

        $expectedJson = [
            'hits' => [
                [
                    "id" => 1,
                    "name" =>  "Fake Monkeys",
                    "venue" =>  "...",
                ]
            ]
        ];
        $response->assertJson($expectedJson);
    }
```

But I'm not able to return a json response like the ```$expectedJson``` above it just returns an empty array :( 
Should I be using something like this (I have tried without success):

```
$this->instance(EngineManager::class, Mockery::mock(Service::class, function ($mock) {
    $mock->shouldReceive('search')->andReturn($expectedJson);
}));
```
Any help or guidance on the best way to handle this is much appreciated.

P.S. @adamwathan do you monitor the email address anymore or is it best to submit questions regarding the course through issues? I don't expect email support 2 years after the course but just wondering ;)

**Comment by adamwathan** [comment]
Haha I still get the emails :) Happy to help out with this, I've never tested Scout before but the fact that they have a NullEngine implementation does make it seem like you should be able to do something with your own fake.

What's the implementation of your FakeEngineManager look like?

**Comment by roarkmccolgan** [comment]
Awesome, thanks a ton Adam

Here it is below, thought I could construct it with a concert I create and just return the array version back...

```
<?php

namespace App\Search;

use Laravel\Scout\Builder;
use Laravel\Scout\Engines\Engine;

class FakeEngineManager extends Engine
{
	private $concert;

	public function __construct($concert = null)
	{
		$this->concert = $concert;
	}

	public function update($models){

	}
	public function delete($models){

	}
	public function search(Builder $builder){
		return $this->concert->toArray();
	}
	public function paginate(Builder $builder, $perPage, $page){

	}
	public function mapIds($results){

	}
	public function map(Builder $builder, $results, $model){

	}
	public function getTotalCount($results){

	}
	public function flush($model){

	}
}
```

**EDIT**
Just realized my initial idea was to fake the engine itself, the above code isn't the engine manager but instead a custom engine [scout docs](https://laravel.com/docs/5.7/scout#custom-engines) so I should use:
```
$this->app->instance(NullEngine::class, new FakeEngine($concert)); //rename it to 'FakeEngine'
```

**Comment by roarkmccolgan** [comment]
I'm trying another way:

```
// $concert = factory...
$this->instance(EngineManager::class, Mockery::mock(EngineManager::class, function ($mock) use($concert) {
            $mock->shouldReceive('createNullDriver')->andReturn(new FakeEngine($concert)); //EngineManager calls createNullDriver when the algolia driver is set to null and returns an instance of the NullEngine
        }));
```
With the idea that it should return my fakeEngine when the EngineManager calls createNullDriver but I'm getting the following error:
```
Received Mockery_2_Laravel_Scout_EngineManager::engine(), but no expectations were specified
```

Is ```andReturn(x)``` not specifying an expectation?

**Comment by roarkmccolgan** [comment]
Going back to the lesson "Stubbing the interface" in "Generating confirmation numbers"
I tried the following:

```
// $concert = factory...
$fakeEngine = Mockery::mock(EngineManager::class, [
    'createNullDriver' => new FakeEngine($concert)
]);
$this->app->instance(EngineManager::class, $fakeEngine);
```

but I get the same error:
```
Received Mockery_2_Laravel_Scout_EngineManager::engine(), but no expectations were specified
```

**Comment by roarkmccolgan** [comment]
Right, got it to work with the last implementation by chaining ```makePartial()``` onto ```mock()```

```php
// $concert = factory...
$fakeEngine = Mockery::mock(EngineManager::class, [
    'createNullDriver' => new FakeEngine($concert)
])->makePartial();
$this->app->instance(EngineManager::class, $fakeEngine);
```

should be able to return the response I need to from the FakeEngine method ```map()``` (not ```search()``` as in my response [here](https://github.com/nothingworksinc/ticketbeast/issues/95#issuecomment-469844991)
